{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "undercontrol.fullname" . }}
  labels:
    {{- include "undercontrol.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.backend.jwt.secret }}
  jwt-secret: {{ .Values.backend.jwt.secret | quote }}
  {{- end }}
  {{- if and (eq .Values.backend.database.type "postgres") .Values.backend.database.postgres.password }}
  postgres-password: {{ .Values.backend.database.postgres.password | quote }}
  {{- end }}
  {{- if .Values.backend.s3.enabled }}
  {{- if .Values.backend.s3.accessKeyId }}
  s3-access-key-id: {{ .Values.backend.s3.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.backend.s3.secretAccessKey }}
  s3-secret-access-key: {{ .Values.backend.s3.secretAccessKey | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.backend.licenseToken }}
  license-token: {{ .Values.backend.licenseToken | quote }}
  {{- end }}
{{- end }}
